---
title: About
---

I am a data analysis and caregiving professional with a Google Data Analytics Certificate and multiple courses on data fundamentals, data-driven decision making, and data preparation. I have acquired skills in PostgreSQL, databases, and spreadsheets, and I can collect, clean, analyze, and visualize data to solve real-world problems and create value for organizations and communities. I am currently working on my Google Advanced Data Analytics Certificate.

I have also demonstrated my leadership and management skills as a General Manager at Papa Johns, where I trained shift managers, worked with the Area Manager, completed weekly inventory and sales data, and created staff schedules. Prior to that, I was a Day Shift Manager, responsible for daily opening processes, product and supply orders, and customer service. Currently, I am providing quality care and support to clients with diverse needs and backgrounds as a Personal Care Assistant. I am passionate about helping others and improving their well-being through attentive and compassionate service.
